USE wo_system;

ALTER TABLE wf_definition
    ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;

ALTER TABLE wf_transition
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;

ALTER TABLE wf_sla_rule
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
