server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: wo-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:192.168.213.100:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:192.168.213.100:8848}
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD_ADDR:192.168.213.100:8858}
  config:
    import: optional:nacos:wo-gateway.yml

nacos:
  remote:
    client:
      grpc:
        server:
          ip: ${NACOS_REMOTE_GRPC_IP:192.168.213.100}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
